name: CI # Name of the workflow, visible in GitHub Actions tab

on: # Events that trigger the workflow
  push: # Run on every push to any branch
    branches:
      - master
  pull_request: # Run on pull requests to any branch
    branches:
      - master

jobs: # Define tasks to run
  build: # Job name (can be anything)
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine

    steps: # Sequence of steps to execute
      - name: Checkout code # Step 1: Get your repository code
        uses: actions/checkout@v3 # Official GitHub action to clone repo

      - name: Set up Python # Step 2: Install Python
        uses: actions/setup-python@v4 # Official action to set up Python
        with:
          python-version: '3.9' # Specify Python version (match your local version)

      - name: Install dependencies # Step 3: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests # Step 4: Placeholder for tests
        run: |
          echo "No tests defined yet. Add your test command here (e.g., pytest)."
          # Replace with actual test command when ready, e.g., pytest